# Generated by Django 3.2.12 on 2022-07-22 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.BooleanField()),
                ('valor', models.BooleanField()),
                ('id_empenho', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Fiscal')),
                ('crea', models.CharField(max_length=150, verbose_name='CREA')),
                ('matricula', models.CharField(max_length=150, verbose_name='Matrícula')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(choices=[('stu', 'Status de Obra'), ('nte', 'Nota de Empenho'), ('emp', 'Empresa'), ('ntf', 'Nota Fiscal'), ('fis', 'Fiscal'), ('obr', 'Obra'), ('con', 'Contrato'), ('adi', 'Aditivos')], max_length=3)),
                ('ref', models.IntegerField(blank=True, default=0)),
                ('tipo', models.CharField(choices=[('c', 'Criado'), ('u', 'Atualizado'), ('a', 'Arquivado'), ('d', 'Deletado')], max_length=1)),
                ('acao', models.CharField(max_length=300)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.CharField(max_length=150)),
                ('ipv4', models.CharField(max_length=15, verbose_name='IP')),
            ],
        ),
        migrations.CreateModel(
            name='Nota_Empenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empenho', models.CharField(choices=[('in', 'Inicial'), ('sd', 'Substituido'), ('st', 'Substituto'), ('co', 'Complementar')], default='in', max_length=2, verbose_name='Tipo de empenho')),
                ('substituto', models.IntegerField(blank=True, default=0, verbose_name='Substituto')),
                ('substituindo', models.IntegerField(blank=True, default=0, verbose_name='Substituindo')),
                ('n_nota', models.IntegerField(unique=True, verbose_name='N. da nota de empenho')),
                ('data', models.DateField(verbose_name='Data de expedição do empenho')),
                ('valor', models.CharField(max_length=20, verbose_name='Valor do empenho(R$)')),
                ('url', models.CharField(default='#', max_length=300, verbose_name='Link da nota do empenho')),
                ('ativo', models.BooleanField(default=False)),
                ('abatido', models.BooleanField(default=False)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Nota_Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_nota', models.CharField(max_length=100, verbose_name='N. da nota fiscal')),
                ('data', models.DateField(verbose_name='Data de expedição fiscal')),
                ('valor', models.CharField(max_length=20, verbose_name='Valor da nota (R$)')),
                ('periodo_inicial', models.DateField(verbose_name='Período inicial da medição')),
                ('periodo_final', models.DateField(verbose_name='Período final da medição')),
                ('url', models.CharField(default='#', max_length=300, verbose_name='Link da nota')),
                ('ativo', models.BooleanField(default=False, null=True)),
                ('obs', models.TextField(verbose_name='Observações')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.nota_empenho')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo_adm', models.CharField(blank=True, default='', max_length=50, verbose_name='Número do Processo Administrativo')),
                ('objeto_da_obra', models.CharField(max_length=150, verbose_name='Objeto da obra')),
                ('populacao_atendida', models.CharField(max_length=150, verbose_name='População atendida')),
                ('valor_previsto', models.CharField(max_length=20, verbose_name='Valor previsto do contrato (R$)')),
                ('n_processo_pagamento', models.CharField(blank=True, default='', max_length=50, verbose_name='Número do Processo de Pagamento')),
                ('engenheiro', models.CharField(default='', max_length=250, verbose_name='Nome do engenheiro responsável')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscalizacao.fiscal', verbose_name='Fiscal responsável')),
                ('fiscal_substituto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituto', to='fiscalizacao.fiscal', verbose_name='Fiscal substituto')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obra_Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('r', 'Responsável'), ('s', 'Suplente'), ('f', 'Férias')], max_length=1)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.fiscal')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.obra')),
            ],
        ),
        migrations.AddField(
            model_name='obra',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscalizacao.status', verbose_name='Situação'),
        ),
        migrations.CreateModel(
            name='Nota_Fiscal_Arquivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_arquivado', models.DateTimeField(auto_now_add=True, verbose_name='Arquivado em')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.nota_fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscalizacao.empresa', verbose_name='Empresa contratada')),
                ('nota_empenho', models.ManyToManyField(blank=True, to='fiscalizacao.Nota_Empenho')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.obra')),
            ],
        ),
    ]
