# Generated by Django 3.2.12 on 2022-05-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscalizacao.nota_empenho'),
        ),
        migrations.AlterField(
            model_name='nota_empenho',
            name='periodo',
            field=models.CharField(max_length=5, verbose_name='Período do empenho'),
        ),
        migrations.AlterField(
            model_name='nota_empenho',
            name='tipo_periodo',
            field=models.CharField(choices=[('a', 'Ano'), ('m', 'Mês'), ('s', 'Semana'), ('d', 'Dia')], default='a', max_length=1, verbose_name='Tipo de período do empenho'),
        ),
        migrations.AlterField(
            model_name='nota_empenho',
            name='url',
            field=models.CharField(default='#', max_length=300, verbose_name='Link da nota do empenho'),
        ),
        migrations.AlterField(
            model_name='nota_empenho',
            name='valor',
            field=models.CharField(max_length=20, verbose_name='Valor do empenho(R$)'),
        ),
    ]
