# Generated by Django 3.2.12 on 2022-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='valor_previsto',
            field=models.CharField(max_length=20, verbose_name='Valor previsto'),
        ),
    ]
