# Generated by Django 4.0.6 on 2022-07-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.BooleanField()),
                ('valor', models.BooleanField()),
                ('id_empenho', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nota_Fiscal_Arquivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_arquivado', models.DateTimeField(auto_now_add=True, verbose_name='Arquivado em')),
            ],
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nota_fiscal',
        ),
        migrations.AddField(
            model_name='contrato',
            name='nota_empenho',
            field=models.ManyToManyField(blank=True, to='fiscalizacao.nota_empenho'),
        ),
        migrations.AddField(
            model_name='nota_empenho',
            name='abatido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota_empenho',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota_empenho',
            name='substituindo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Substituindo'),
        ),
        migrations.AddField(
            model_name='nota_empenho',
            name='substituto',
            field=models.IntegerField(blank=True, default=0, verbose_name='Substituto'),
        ),
        migrations.AddField(
            model_name='nota_empenho',
            name='tipo_empenho',
            field=models.CharField(choices=[('in', 'Inicial'), ('sd', 'Substituido'), ('st', 'Substituto'), ('co', 'Complementar')], default='in', max_length=2, verbose_name='Tipo de empenho'),
        ),
        migrations.AddField(
            model_name='nota_fiscal',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obra',
            name='n_processo_adm',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número do Processo Administrativo'),
        ),
        migrations.AddField(
            model_name='obra',
            name='n_processo_pagamento',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número do Processo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='nota_empenho',
            name='periodo',
            field=models.CharField(max_length=5, verbose_name='Período do empenho'),
        ),
        migrations.AlterField(
            model_name='nota_empenho',
            name='tipo_periodo',
            field=models.CharField(choices=[('a', 'Ano'), ('m', 'Mês'), ('s', 'Semana'), ('d', 'Dia')], default='a', max_length=1, verbose_name='Tipo de período do empenho'),
        ),
        migrations.AlterField(
            model_name='nota_empenho',
            name='url',
            field=models.CharField(default='#', max_length=300, verbose_name='Link da nota do empenho'),
        ),
        migrations.AlterField(
            model_name='nota_empenho',
            name='valor',
            field=models.CharField(max_length=20, verbose_name='Valor do empenho(R$)'),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='n_nota',
            field=models.CharField(max_length=100, verbose_name='N. da nota fiscal'),
        ),
        migrations.DeleteModel(
            name='Aditivos',
        ),
        migrations.AddField(
            model_name='nota_fiscal_arquivada',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.nota_fiscal'),
        ),
    ]
