# Generated by Django 4.0.6 on 2022-07-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0002_aditivo_nota_fiscal_arquivada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='ativo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
