# Generated by Django 3.2.12 on 2022-05-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0002_auto_20220526_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='nota_fiscal',
            new_name='nota_empenho',
        ),
    ]
