# Generated by Django 3.2.12 on 2022-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0003_alter_nota_fiscal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_fiscal',
            name='tipo_periodo',
            field=models.CharField(choices=[('a', 'Ano'), ('m', 'Mês'), ('s', 'Semana'), ('d', 'Dia')], default='a', max_length=1, verbose_name='Tipo de Período'),
        ),
    ]
