# Generated by Django 3.2.12 on 2022-05-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0003_rename_nota_fiscal_contrato_nota_empenho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='nota_empenho',
        ),
        migrations.AddField(
            model_name='contrato',
            name='nota_empenho',
            field=models.ManyToManyField(to='fiscalizacao.Nota_Empenho'),
        ),
    ]
