# Generated by Django 3.2.12 on 2022-05-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0004_auto_20220526_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_empenho',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='n_nota',
            field=models.CharField(max_length=100, verbose_name='N. da nota fiscal'),
        ),
    ]
