# Generated by Django 3.2.12 on 2022-05-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0005_auto_20220527_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='nota_empenho',
            field=models.ManyToManyField(blank=True, to='fiscalizacao.Nota_Empenho'),
        ),
    ]
