# Generated by Django 3.2.12 on 2022-06-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0006_alter_contrato_nota_empenho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_Fiscal_Arquivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_arquivado', models.DateTimeField(auto_now_add=True, verbose_name='Arquivado em')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.nota_fiscal')),
            ],
        ),
        migrations.DeleteModel(
            name='Aditivos',
        ),
    ]
