# Generated by Django 3.2.12 on 2022-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0007_auto_20220601_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='n_processo_adm',
            field=models.CharField(default='', max_length=50, verbose_name='Valor previsto do contrato (R$)'),
        ),
        migrations.AddField(
            model_name='obra',
            name='n_processo_pagamento',
            field=models.CharField(default='', max_length=50, verbose_name='Valor previsto do contrato (R$)'),
        ),
    ]
