# Generated by Django 3.2.12 on 2022-06-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0008_auto_20220602_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.BooleanField()),
                ('valor', models.BooleanField()),
                ('id_empenho', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='obra',
            name='n_processo_adm',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número do Processo Administrativo'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='n_processo_pagamento',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número do Processo de Pagamento'),
        ),
    ]
