# Generated by Django 3.2.12 on 2022-06-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0009_auto_20220602_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_empenho',
            name='abatido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota_empenho',
            name='tipo_empenho',
            field=models.CharField(choices=[('in', 'Inicial'), ('sd', 'Substituido'), ('st', 'Substituto'), ('co', 'Complementar')], default='in', max_length=2, verbose_name='Tipo de empenho'),
        ),
    ]
