# Generated by Django 3.2.12 on 2022-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0010_auto_20220602_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_empenho',
            name='substituindo',
            field=models.IntegerField(blank=True, default=0, verbose_name='N. da nota de empenho'),
        ),
        migrations.AddField(
            model_name='nota_empenho',
            name='substituto',
            field=models.IntegerField(blank=True, default=0, verbose_name='N. da nota de empenho'),
        ),
    ]
