# Generated by Django 3.2.12 on 2022-07-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0011_auto_20220603_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_empenho',
            name='substituindo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Substituindo'),
        ),
        migrations.AlterField(
            model_name='nota_empenho',
            name='substituto',
            field=models.IntegerField(blank=True, default=0, verbose_name='Substituto'),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='empenho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.nota_empenho'),
        ),
    ]
