# Generated by Django 3.2.12 on 2022-07-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0012_auto_20220720_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='empenho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscalizacao.nota_empenho'),
        ),
    ]
